### ISSUE TITLE
Error occurs when no feature assign to some clusters

### ISSUE THREAD

**Issue by SYFT** [Kanatoko/XBOS-anomaly-detection#2]
https://github.com/Kanatoko/XBOS-anomaly-detection/blob/41ee7805cc866c5bcf1850954c790d9b046ae79b/xbos.py#L26

Error occurs when no feature assign to some clusters.
kmeans.predict doesn't promise to assign at least one feature to some clusters.

**Comment by Kanatoko** [comment]
Thank you.
Can I ask the size of data points and clusters?

**Comment by SYFT** [comment]
clusters 25
data point > 8*10^8
This error can be fixed by convert cluster_score to dict.
By the way, this implement consump too much memory, I think it could benefit from minibatch-kmeans.

**Comment by Kanatoko** [comment]
@boukicher 
No, there is no paper about XBOS.
